using System.Globalization;
using System.IO;
using System.Text;

namespace SkinEditorNext.Services;

public sealed record NewSkinSettings(
    int SkinType,
    string Title,
    string Maker,
    string Thumbnail,
    int Width,
    int Height);

public sealed record Lr2DstSpec(
    int Time,
    int X,
    int Y,
    int Width,
    int Height,
    int Acc,
    int Alpha,
    int Red,
    int Green,
    int Blue,
    int Blend,
    int Filter,
    double Angle,
    int Center,
    int Loop,
    int Timer,
    int Op1,
    int Op2,
    int Op3,
    int Op4,
    int Op5);

// Keep every generated command in LR2's original CSV field order.
// If a new object type is added later, copy the field order from LR2_skinload.cpp first.
public sealed class Lr2SkinWriter
{
    public static readonly NewSkinSettings DefaultSettings = new(
        0,
        "New LR2 Skin",
        string.Empty,
        string.Empty,
        1280,
        720);

    public static string CreateNewSkin(NewSkinSettings settings)
    {
        // LR2's skin selector reads #INFORMATION and #RESOLUTION before the full skin load.
        // Always write explicit width/height so generated skins do not fall back to 640x480.
        var lines = new List<string>
        {
            "// Generated by SkinEditorNext",
            CsvUtil.Join(["#INFORMATION", settings.SkinType.ToString(CultureInfo.InvariantCulture), settings.Title, settings.Maker, settings.Thumbnail]),
            CsvUtil.Join(["#RESOLUTION", settings.Width.ToString(CultureInfo.InvariantCulture), settings.Height.ToString(CultureInfo.InvariantCulture)]),
            "#ENDOFHEADER",
            string.Empty,
            "#STARTINPUT,100",
            "#LOADSTART,0",
            "#LOADEND,1000",
            "#PLAYSTART,3200",
            "#FADEOUT,500",
            "#CLOSE,3400"
        };

        return string.Join(Environment.NewLine, lines) + Environment.NewLine;
    }

    public static string ImageLine(string relativePath)
    {
        return CsvUtil.Join(["#IMAGE", NormalizePath(relativePath)]);
    }

    public static string FontLine(int size = 20, int thickness = 5, int edge = 2, string name = "MS Gothic")
    {
        return CsvUtil.Join([
            "#FONT",
            size.ToString(CultureInfo.InvariantCulture),
            thickness.ToString(CultureInfo.InvariantCulture),
            edge.ToString(CultureInfo.InvariantCulture),
            name
        ]);
    }

    public static IReadOnlyList<string> ImageObjectLines(int imageSlot, int sourceWidth, int sourceHeight, Lr2DstSpec dst)
    {
        // imageSlot is the zero-based #IMAGE registration order, not a number written on #IMAGE itself.
        return [
            SourceLine("#SRC_IMAGE", 0, imageSlot, 0, 0, sourceWidth, sourceHeight, 1, 1, 0, 0, 0, 0, 0, 0, 0),
            DstLine("#DST_IMAGE", 0, dst)
        ];
    }

    public static IReadOnlyList<string> NumberObjectLines(int imageSlot, int sourceWidth, int sourceHeight, int valueOption, Lr2DstSpec dst)
    {
        return [
            SourceLine("#SRC_NUMBER", 0, imageSlot, 0, 0, sourceWidth, sourceHeight, 10, 1, 0, 0, valueOption, 0, 0, 0, 0),
            DstLine("#DST_NUMBER", 0, dst)
        ];
    }

    public static IReadOnlyList<string> TextObjectLines(int fontSlot, int textKind, int align, Lr2DstSpec dst)
    {
        // #SRC_TEXT has a different field shape from image-like sources, so do not route it through SourceLine.
        return [
            CsvUtil.Join([
                "#SRC_TEXT",
                "0",
                fontSlot.ToString(CultureInfo.InvariantCulture),
                textKind.ToString(CultureInfo.InvariantCulture),
                align.ToString(CultureInfo.InvariantCulture),
                "0",
                "0",
                "0",
                "0",
                "0"
            ]),
            DstLine("#DST_TEXT", 0, dst)
        ];
    }

    private static string SourceLine(
        string command,
        int index,
        int graph,
        int x,
        int y,
        int width,
        int height,
        int divX,
        int divY,
        int cycle,
        int timer,
        int op1,
        int op2,
        int op3,
        int op4,
        int op5)
    {
        // Generic image-like #SRC_* fields:
        // command,n,graph,x,y,w,h,div_x,div_y,cycle,timer,op1,op2,op3,op4,op5
        return CsvUtil.Join([
            command,
            index.ToString(CultureInfo.InvariantCulture),
            graph.ToString(CultureInfo.InvariantCulture),
            x.ToString(CultureInfo.InvariantCulture),
            y.ToString(CultureInfo.InvariantCulture),
            Math.Max(1, width).ToString(CultureInfo.InvariantCulture),
            Math.Max(1, height).ToString(CultureInfo.InvariantCulture),
            Math.Max(1, divX).ToString(CultureInfo.InvariantCulture),
            Math.Max(1, divY).ToString(CultureInfo.InvariantCulture),
            cycle.ToString(CultureInfo.InvariantCulture),
            timer.ToString(CultureInfo.InvariantCulture),
            op1.ToString(CultureInfo.InvariantCulture),
            op2.ToString(CultureInfo.InvariantCulture),
            op3.ToString(CultureInfo.InvariantCulture),
            op4.ToString(CultureInfo.InvariantCulture),
            op5.ToString(CultureInfo.InvariantCulture)
        ]);
    }

    private static string DstLine(string command, int index, Lr2DstSpec dst)
    {
        // Generic #DST_* fields:
        // command,n,time,x,y,w,h,acc,a,r,g,b,blend,filter,angle,center,loop,timer,op1..op5
        return CsvUtil.Join([
            command,
            index.ToString(CultureInfo.InvariantCulture),
            dst.Time.ToString(CultureInfo.InvariantCulture),
            dst.X.ToString(CultureInfo.InvariantCulture),
            dst.Y.ToString(CultureInfo.InvariantCulture),
            Math.Max(1, dst.Width).ToString(CultureInfo.InvariantCulture),
            Math.Max(1, dst.Height).ToString(CultureInfo.InvariantCulture),
            dst.Acc.ToString(CultureInfo.InvariantCulture),
            Math.Clamp(dst.Alpha, 0, 255).ToString(CultureInfo.InvariantCulture),
            Math.Clamp(dst.Red, 0, 255).ToString(CultureInfo.InvariantCulture),
            Math.Clamp(dst.Green, 0, 255).ToString(CultureInfo.InvariantCulture),
            Math.Clamp(dst.Blue, 0, 255).ToString(CultureInfo.InvariantCulture),
            dst.Blend.ToString(CultureInfo.InvariantCulture),
            dst.Filter.ToString(CultureInfo.InvariantCulture),
            dst.Angle.ToString(CultureInfo.InvariantCulture),
            dst.Center.ToString(CultureInfo.InvariantCulture),
            dst.Loop.ToString(CultureInfo.InvariantCulture),
            dst.Timer.ToString(CultureInfo.InvariantCulture),
            dst.Op1.ToString(CultureInfo.InvariantCulture),
            dst.Op2.ToString(CultureInfo.InvariantCulture),
            dst.Op3.ToString(CultureInfo.InvariantCulture),
            dst.Op4.ToString(CultureInfo.InvariantCulture),
            dst.Op5.ToString(CultureInfo.InvariantCulture)
        ]);
    }

    public static string ToLr2LoadPath(string fullPath, string fallbackBaseDirectory)
    {
        var normalizedFullPath = Path.GetFullPath(fullPath);
        var fullDirectory = Directory.Exists(normalizedFullPath)
            ? normalizedFullPath
            : Path.GetDirectoryName(normalizedFullPath);

        var directory = string.IsNullOrWhiteSpace(fullDirectory)
            ? new DirectoryInfo(Path.GetFullPath(fallbackBaseDirectory))
            : new DirectoryInfo(fullDirectory);

        while (directory is not null)
        {
            var lr2FilesRoot = Path.Combine(directory.FullName, "LR2files");
            if (IsSameOrChildPath(normalizedFullPath, lr2FilesRoot))
            {
                return NormalizePath(Path.GetRelativePath(directory.FullName, normalizedFullPath));
            }

            directory = directory.Parent;
        }

        return NormalizePath(Path.GetRelativePath(fallbackBaseDirectory, normalizedFullPath));
    }

    private static bool IsSameOrChildPath(string path, string root)
    {
        var normalizedPath = Path.TrimEndingDirectorySeparator(Path.GetFullPath(path));
        var normalizedRoot = Path.TrimEndingDirectorySeparator(Path.GetFullPath(root));
        return normalizedPath.Equals(normalizedRoot, StringComparison.OrdinalIgnoreCase) ||
               normalizedPath.StartsWith(normalizedRoot + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase) ||
               normalizedPath.StartsWith(normalizedRoot + Path.AltDirectorySeparatorChar, StringComparison.OrdinalIgnoreCase);
    }
    private static string NormalizePath(string path)
    {
        return path.Replace('/', '\\').Trim();
    }
}
